image: node:10.16.0

pages:
  cache:
    paths:
    - documentation/node_modules/

  script:
  - ls
  - cd documentation
  - npm install
  - npm run build
  artifacts:
    paths:
    - public

  only:
  - master