image: node:10.16.0

pages:
  cache:
    paths:
    - documentation/node_modules/

  script:
  - cd documentation && npm install
  - cd documentation && npm run build
  artifacts:
    paths:
    - public

  only:
  - master